# Configuracoes de Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/telefonia_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Geracao e Atualizacao Automatica de Tabelas via Hibernate
spring.jpa.hibernate.ddl-auto=update

# Dialeto e Formatacao de Logs SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.format_sql=true

#Defini nossa chave secreta e o emissor da aplicação
api.security.token.secret=${JWT_SECRET:minha-chave-secreta-super-segura}